<html>
<head>
<title>Frazier Laboratory - Internal Website</title>
<link rel="stylesheet" href="/SWHLabPHP/src/templates/01_barebones/style.css">
<style>
body {
	padding: 0px;
    margin: 0px;
	font-family: sans-serif;
    background-color: #F6F6F6;
}
.box_whole{
    margin: 50 0 50 0;
    border-style: solid;
    border-color: #25658a;
    border-width: 1px 1px 1px 10px;
	padding: 10px;
    box-shadow: 5px 5px 10px  rgba(0, 0, 0, 0.15); 
    background-color: white;
}
.box_top{
	font-size: 175%;
    font-weight: bold; 
	padding-bottom: 5px;
}
.box_content{
    line-height: 150%;
    padding-left: 20px;
}
.cat_subtitle{    
    position: relative;
    left: -20px;    
    padding-top: 10px;
    font-weight: bold;
}
.cat_subsubtitle{
    position: relative;
    left: -20px;   
    font-size: 80%;
    font-style: italic;
    line-height: 100%;
}
.holder{
    width: 90%;
	margin: 0 auto;
}
.banner{
	background-image: url(/files/ap.png);
    background-size: cover;
	padding-top: 20px;
	padding-bottom: 20px;
	background-position: left bottom;
}
.li2{
    margin-left: 25px;
}


</style>


</head>
<body>




<div class='banner'>
<div style="font-size: 250%; font-weight: bold; padding-left: 20px; position: relative; top: -15px;">Frazier Laboratory</div>
<div style="font-size: 80%; font-style: italic; padding-left: 20px; position: relative; top: -22px;">
    <?php 
    echo "Page generated by ";
    echo $_SERVER['SERVER_ADDR'];
    echo " on ";
    $d = new DateTime('', new DateTimeZone('US/Eastern')); 
    echo $d->format('Y-m-d H:i:s');
    ?>
</div>

</div>



<?php

function link_xdrive($fname,$title=False){
    // given a path starting with X:\, display a link to the file and along with its age
    // currently this path MUST start with "X:\\Data\\"
    
    if (!file_exists($fname)) {
        echo "<span style='background-color: yellow;'>$fname not found!</div>";
        return;
    }
    
    if (!$title) $title=basename($fname);
    
    // determine file age
    $ageSec=time()-filemtime($fname);
    $ageMin=$ageSec/60;
    $ageHr=$ageMin/60;
    $ageDy=$ageHr/24;
    $ageYr=$ageDy/365.25;
    $ageString=date("F d Y H:i:s.", filemtime($fname));
    
    // determine string formatting
    if ($ageHr<1) $ageString=sprintf("%.02f min", $ageMin);
    else if ($ageDy<1) $ageString=sprintf("%.02f hr", $ageHr); 
    else if ($ageDy<60) $ageString=sprintf("%.02f d", $ageDy);
    else $ageString=sprintf("%.02f yr", $ageYr);
    
    // color based on age
    if ($ageDy<2) { 
        $colorFG="#000000";
        $colorBG="#FFFF00";
    }
    else if ($ageDy<7) {  
        $colorFG="#000000";
        $colorBG="#a9f3ca";  
    }
    else if ($ageDy<14) {
        $colorFG="#000000";
        $colorBG="#eaffea";
    }
    else {
        $colorFG="#999999";
        $colorBG="#FFFFFF";
    }
    
    // write the colorized link
    $link=str_replace("X:\\Data\\",'/dataX/',$fname);
    echo "<span style='background-color: $colorBG; padding-left: 4px; padding-right: 4px;'>";
    echo "<a href='$link'>$title</a>";
    echo "<span style='color: $colorFG; font-size: 70%'>";
    echo " $ageString</span></span>";
    
}

?>


<div class='holder'>

<div class='box_whole'>
	<div class='box_top'>Pinned Projects</div>
	<div class='box_content'>    
        
        <div class="cat_subtitle">Aging BLA Study</div>
            <li>March, 2017 - round 1 (SH): <a href='/SWHLabPHP/recode/src/?view=abf&fldr=X:\Data\projects\2017-04-24%20aging%20BLA\2017-04-24%20BLA%20aging%20round1&frames'>data</a>,
                              <a href='/dataX/projects/2017-04-24%20aging%20BLA/2017-04-24%20BLA%20aging%20round1/onenote_summary.pdf'>notes</a>,
                              <?php link_xdrive('X:\Data\projects\2017-04-24 aging BLA/2017-04-24 BLA aging round1/summary aging round 1.pdf','summary'); ?>
            <li>October, 2017 - round 2 (SH, TS, and JT): 
                            <a href="/SWHLabPHP/recode/src/?view=abf&fldr=X:\Data\projects\2017-04-24%20aging%20BLA\2017-10-10%20BLA%20aging%20round2&frames">data</a>, 
                            <?php link_xdrive('X:\Data\projects\2017-04-24 aging BLA\2017-10-10 BLA aging round2\summary round 2.pdf','summary'); ?>
        
        <div class="cat_subtitle">AT1-Cre Experiments</div>
        
            <li>
            NTS ChR2:             
                    <a href='/SWHLabPHP/recode/src/?view=abf&fldr=X:\Data\projects\2017-01-09%20AT1-Cre%20mice\2017-01-09%20global%20expression%20NTS&frames'>data (global)</a>,
                    <a href='/SWHLabPHP/recode/src/?view=abf&fldr=X:\Data\projects\2017-01-09%20AT1-Cre%20mice\2017-10-05%20nodose%20injection%20NTS&frames'>data (nodose)</a>,
                    <?php link_xdrive('X:\Data\projects\2017-01-09 AT1-Cre mice/summary_nts.pdf','summary (global and nodose)'); ?>
            
            <li>
            MPO injection (ChR2 and halo):
            <a href='/SWHLabPHP/recode/src/?view=abf&fldr=X:\Data\projects\2017-01-09%20AT1-Cre%20mice\2017-08-22%20MPO%20injection%20PVN&frames'>data</a>, 
            <?php link_xdrive('X:\Data\projects\2017-01-09 AT1-Cre mice/summary_mpo.pdf','summary'); ?>

        <div class="cat_subtitle">Misc</div>
        
        <li>OT-Cre Experiments: <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&fldr=X:\Data\projects\2017-06-16%20OT-Cre%20mice\data&frames">data</a>, <a href='/dataX/projects/2017-06-16%20OT-Cre%20mice/notes/'>reports</a>
        
        
        
        
    </div>
</div>
    
    

<div class='box_whole'>
	<div class='box_top'>Live Data Browsers</div>
    <li><a href="/SWHLabPHP/recode/src/?view=abf">ABF Browser</a>
    <li><a href="SWHLabPHP/src/">Linescan Viewer</a>
    <li><a href="/dataX/projects/">Apache File Browser</a>
</div>
    
    
<div class='box_whole'>
	<div class='box_top'>Project History</div>
	<div class='box_content'>    
        <div class="cat_subsubtitle">Links here aim to summarize primary efforts and findings of large projects in one or two links.<br>For full project details use your file browser to explore all contents of the project folder.<br><br></div>
        
        <li>Aging BLA halorhodopsin (SH): <a href='/SWHLabPHP/recode/src/?view=abf&fldr=X:\Data\projects\2017-07-17%20BLA%20halo%20aging%20Bizon\data&frames'>data</a>, <?php link_xdrive('X:\Data\projects\2017-07-17 BLA halo aging Bizon/summary.pdf','summary'); ?>
        <li>Aging BLA study (round 1, KK and SH): <a href='/dataX/projects/2017-04-24%20aging%20BLA/2017-04-24%20BLA%20aging%20round1/onenote_summary.pdf'>notes</a>, <?php link_xdrive('X:\Data\projects\2017-04-24 aging BLA/2017-04-24 BLA aging round1/analysis/2017-10-17.pdf','summary'); ?>
        <li>AT1-Cre PVN (ChR2 injected in MPO) BLS-evoked glu synapses onto VP+ MCNs: <?php link_xdrive('X:\Data\projects\2017-01-09 AT1-Cre mice/2017-08-22 MPO injection PVN/notes/2017-09-01 AT1 MPO PVN ChR2 summary.pdf','summary'); ?>
        <li>AT1-Cre NTS (ChR2 expressed globally) demonstrating GLU: <?php link_xdrive('X:\Data\projects\2017-01-09 AT1-Cre mice\summary_nts.pdf','summary'); ?>
        <li>OTR-Cre (GCaMP6f injected in mPFC) fiber photometry: <a href='https://www.youtube.com/watch?v=r5iyD7B55EE'>video puffing glutamate</a> 
        <li>OT signaling in the LHA (response to TGOT and OT-Cre/ChR2 BLS): <a href='/SWHLabPHP/recode/src/?view=abf&fldr=X:\Data\projects\misc\2017-05-15%20SH%20MS%20LHA%20TGOT\data&frames'>data</a>, <?php link_xdrive('X:\Data\projects\misc/2017-05-15 SH MS LHA TGOT/onenote_notes3.pdf','summary'); ?> (map below)
        <li>CRH reporter isotonic vs hypertonic saline injection (SH): <a href='/SWHLabPHP/recode/src/?view=abf&fldr=X:\Data\projects\2017-07-31%20CRH-tdTom%20mice&frames'>data</a>, <a href='/dataX/projects/2017-07-31%20CRH-tdTom%20mice/onenote_summary.pdf'>notes</a>, <?php link_xdrive('X:\Data\projects\2017-07-31 CRH-tdTom mice/summary.pdf','summary'); ?>
        <li>GCaMP6f field imaging in OT-Cre and GABA-Cre (PFC injection): <a href='/dataX/projects/misc/2017-05-10%20SH%20GCaMP6f%20PFC%20OXTR%20and%20GABA%20cre/onenote_notes.pdf'>notes</a>, <?php link_xdrive('X:\Data\projects\misc/2017-05-10 SH GCaMP6f PFC OXTR and GABA cre/summary 2017-06-11.pdf','summary'); ?>
        <li>Evoked GLU release in the NAc: <a href='/dataX/projects/misc/2017-06-07%20SH%20NAC%20GLU%20for%20Peris/onenote_summary.pdf'>notes</a>, <a href='/dataX/projects/misc/2017-06-07%20SH%20NAC%20GLU%20for%20Peris/summary.png'>ephys figure</a>, and <a href='/dataX/projects/misc/2017-06-07%20SH%20NAC%20GLU%20for%20Peris/notes/diagram.png'>diagram</a>
        <li>PVN astrocyte calcium imaging in CRH/tdTom mice: <a href="/dataX/projects/misc/2017-01-11%20PVN%20astrocyte%20calcium%20imaging/">results</a>, <?php link_xdrive('X:\Data\projects\misc/2017-01-11 PVN astrocyte calcium imaging/analysis/onenote_summary.pdf','summary'); ?>
        <li>OXT Signaling in the Piriform Cortex: <a href='/SWHLabPHP/recode/src/?view=abf&fldr=X:\Data\projects\2016-09-01%20PIR%20TGOT\data&frames'>data</a>, manuscript (from 2016-01-02) is in Jason's cloud account
        <li>TGOT induces sIPSCs in mouse BNST: <?php link_xdrive('X:\Data\projects\misc/2014-08 TGOT mouse BNST/summary.pdf','summary'); ?> (first demonstrated action of TGOT in our lab)
        <li>OTR-Cre (ChR2 injected in BNST) local synapses, synapses in lateral septum and hippocampus: <a href='/dataX/projects/misc/2014-07-10%20OTR%20BNST%20ChR2/summary.txt'>summary</a> and <?php link_xdrive('X:\Data\projects\misc/2014-07-10 OTR BNST ChR2/paper outline.pdf','outline'); ?>
        <li>OTR-Cre (ChR2 injected in VTA) intrinsic and synaptic properties: <?php link_xdrive('X:\Data\projects\misc/2014-07 VTA OXTR OPTO/results.pdf','summary'); ?>
        <li>Two-photon calcium imaging in OT+ MCNs (OTA vs TGOT): <?php link_xdrive('X:\Data\projects\misc/2014-07 TGOT magnocellular two-photon/2P MCN TGOT 2014-08-11.pdf','R01 grant figure and follow-up'); ?>
        <li>For projects contributed to before 2017, browse the X:\Data Analysis\ folder and read peoples' lab notebooks
        
	</div>
</div>


<div class='box_whole'>
	<div class='box_top'>Animal Characterization</div>
	<div class='box_content'>
        <a name='reporter_ottom'></a>
        <div class="cat_subtitle">OT-Cre/Tom Mouse Line</div>
        <div class="cat_subsubtitle">This mouse line expresses tdTomato in OT-Cre neurons</div>
        
        <li>brain map: 
        <a href="dataX/projects/2017-06-16 OT-Cre mice/reporter brain map/male/index.html">male</a>, 
        <a href="dataX/projects/2017-06-16 OT-Cre mice/reporter brain map/female/images/index.html">female</a>, 
        <a href="dataX/projects\2017-06-16 OT-Cre mice\reporter brain map\2017-11-09 PFC\map.jpg">PFC male</a><br> 
        
        <li>PVN validation: 
        <a href="/dataX/projects\2017-06-16 OT-Cre mice\data\fishing\2017-06-16 mannitol linescans\data\linescans\2p/ZSeries-06302017-1049-699/MIP/out_merge">merged</a>,
        <a href="/dataX/projects\2017-06-16 OT-Cre mice\data\fishing\2017-06-16 mannitol linescans\data\linescans\2p/ZSeries-06302017-1049-699/MIP/animated.gif">aniGray</a>,
        <a href="/dataX/projects\2017-06-16 OT-Cre mice\data\fishing\2017-06-16 mannitol linescans\data\linescans\2p/ZSeries-06302017-1049-699/MIP/animated2.gif">aniCol</a><br>
        
        <li>IHC Notes: <a href='/dataX/projects/2017-06-16%20OT-Cre%20mice/reporter%20brain%20map/onenote_summary.pdf'>regarding antibodies and off-target Cre expression</a>

        <a name='reporter_otchr2'></a>
        <div class="cat_subtitle">OT-Cre/ChR2 Mouse Line</div>
        <div class="cat_subsubtitle">This mouse line expresses ChR2 in OT-Cre neurons. Although the rate of false-positive Cre/ChR2 expression may be 1 in 10,000, it is enough to label several non-OT neurons per slice. This means light-evoked currents (i.e., glutamate) may originate from non-OT neurons. This line is no longer being actively bred.</div>
        <li><a href='/dataX/projects/2017-04-19%20OT-ChR2%20mice/2016-06-13%20OT%20ChR2%20brain%20map/OT-001/pvn-son-lowqual.png'>PVN/SON slice</a> (20 micron slice from Yalun)
        <li><a href='/dataX/projects/2017-04-19%20OT-ChR2%20mice/2016-06-13%20OT%20ChR2%20brain%20map/OT-001/PIR-montage/pir_montage.png'>PIR slice</a> (20 micron slice from Yalun)
        
        <a name='reporter_crhtom'></a>
        <div class="cat_subtitle">CRH-Cre/Tom Mouse Line</div>
        <div class="cat_subsubtitle">This mouse line expresses tdTomato in OT-Cre neurons</div>
        
        <li>brain map (male): 
        <a href="/dataX/projects\2017-07-31 CRH-tdTom mice\reporter brain map/montage%2017801%20v2/enhanced_tdTom.png">Tom</a>,
        <a href="/dataX/projects\2017-07-31 CRH-tdTom mice\reporter brain map/montage%2017801%20v2/enhanced_best.png">Tom+NP1</a><br>
        
        <li>PVN validation: 
        <a href="/dataX/projects\2017-07-31 CRH-tdTom mice\reporter brain map/2p%20pvn%20flat/enhanced.png">Tom+NP1</a><br>

        <a name='rat'></a>
        <div class="cat_subtitle">Rat Neuroanatomy</div>
        <li>Rat pup (p16), horizontally sectioned, slice containing BLA:
        <a href="/dataX/projects\misc\2017-07-19 TS practice\imaging/montage_enhanced.jpg">original</a> and 
        <a href="/dataX/projects\misc\2017-07-19 TS practice\imaging/annotated.png">annotated</a><br>
        <li>Aged rat (22mo), coronally sectioned, amygdalar complex (Todd)
	</div>
</div>



<div class='box_whole'>
	<div class='box_top'>Miscellaneous</div>
	<div class='box_content'>
        <li><?php link_xdrive('files/illustrations/filter_cubes/index.html','Filter cube charts'); ?>
        <li><a href="https://github.com/swharden/two-photon/tree/master/documentation/startup-and-shutdown">2P startup and shutdown notes</a>
        <li><a href="https://github.com/swharden/two-photon/tree/master/software/time-series-analysis/2016-12-02-excel">2P time series (video) analysis with Excel</a> (for GCaMP or Fluo-4 AM experiments)
        <li><a href="files/2p-shutter.pdf">two photon shutter build</a>
        <li><a href="https://youtu.be/VrKIg0IQL98">old 2P laser calibration video</a> (see note about <a href="https://youtu.be/Bt9zSfinwFA">VVS</a>)
        
        <li>Calcium imaging using Fluo4 is possible in tdTomato animals: <a href="https://www.youtube.com/watch?v=gpVVqQLCe8Y">YouTube video</a>, <a href="/dataX/projects/misc/2017-03-10%20tdTomato%20fluo4/">data folder</a>, and <a href="/dataX/projects/misc/2017-03-10%20tdTomato%20fluo4/onenote_notes.pdf">notes</a>.
        <li><a href="files/internal_k2.png">EPSCs and IPSCs are divergent at -70mV</a>using Scott's "K2" internal solution.
        <li><a href="files/scope_frazier_vs_foster.png">comparison of slice optics between two similar microscopes</a>
        <li><a href='https://youtu.be/4z3JDsVqICE'>time series calcium imaging analysis video tutorial</a> (for GCaMP or Fluo-4 AM experiments)
        <li>GCaMP6f field imaging videos: <a href='https://www.youtube.com/watch?v=1OHvPi1TbII'>GABA-Cre PFC +GLU</a>, <a href='https://www.youtube.com/watch?v=EEuXCMoRtsw'>GABA-Cre mPFC +TGOT</a>, <a href='https://www.youtube.com/watch?v=zYcEWnD3GCs'>GABA-Cre iPFC +TGOT</a>, <a href='https://youtu.be/tXZq13Gtk1I'>OTR-Cre PFC +TGOT</a>
        <li>Fiber photometry video <a href='https://www.youtube.com/watch?v=r5iyD7B55EE'>OTR-Cre PFC +GLU</a> and <a href='https://github.com/swharden/ROI-Analysis-Pipeline/tree/master/pyFiber'>software</a>
        <li>Two-photon whole-cell experiment: <a href='/dataX/projects/misc/2017-06-08%20SH%202p%20F5%20tests/result_egta.png'>EGTA vs EGTA-Free internal</a>, <a href='/dataX/projects/misc/2017-06-08%20SH%202p%20F5%20tests/result_protocol.png'>back-acting AP protocol</a>
	</div>
</div>



<div class='box_whole'>
	<div class='box_top'>Technical</div>
	<div class='box_content'>
        <li>View a list of <a href='files/activeFolders/results.csv.html'>active folders (organized by date)</a> for the history of the lab.
        <li>Github projects <a href="https://github.com/swharden/SWHLab">SWHLab</a>, <a href="https://github.com/swharden/SWHLabPHP">SWHLabPHP</a>, <a href="https://github.com/swharden/two-photon">two-photon</a>, and <a href='https://github.com/swharden/swh2p'>SWH2P</a>
        <li>Display this server's <a href="phpinfo.php">PHP information</a>
        <li>View the live <a href='http://192.168.1.9/SWHLabPHP/recode/src/?view=commands&viewLog'>command log</a>
        
	</div>
</div>




</div>
<img src="files/celldie.png" style='width: 100%;'>
<br><br><br>
</body>
</html>
